server/urls.py
from django.conf.urls import *

urlpatterns = patterns('server.views',
    #front. page
    url(r'^$', 'index', name='home'),

    # Add computer
    url(r'^new/computer/', 'new_computer', name='new_computer'),
    # Add secret
    url(r'^new/secret/(?P<computer_id>.+)/', 'new_secret', name='new_secret'),

    # secret info
    url(r'^info/secret/(?P<secret_id>.+)/', 'secret_info', name='secret_info'),

    #computerinfo
    url(r'^info/(?P<computer_id>.+)/', 'computer_info', name='computer_info'),

    #request
    url(r'^request/(?P<secret_id>.+)/', 'request', name='request'),
    #retrieve
    url(r'^retrieve/(?P<request_id>.+)/', 'retrieve', name='retrieve'),
    #approve
    url(r'^approve/(?P<request_id>.+)/', 'approve', name='approve'),
    #checkin
    url(r'^checkin/', 'checkin', name='checkin'),
    #manage
    url(r'^manage-requests/', 'managerequests', name='managerequests'),
)

server/models.py
from django.db import models
from django.contrib.auth.models import User, Permission
from django.contrib.contenttypes.models import ContentType
from django_extensions.db.fields.encrypted import EncryptedCharField

from django.core.exceptions import ValidationError

# Create your models here.
class Computer(models.Model):
    #recovery_key = models.CharField(max_length=200, verbose_name="Recovery Key")
    serial = models.CharField(max_length=200, verbose_name="Serial Number")
    username = models.CharField(max_length=200, verbose_name="User Name")
    computername = models.CharField(max_length=200, verbose_name="Computer Name")
    last_checkin = models.DateTimeField(blank=True,null=True)
    def __unicode__(self):
        return self.computername
    class Meta:
        ordering = ['serial']
        permissions = (
                    ('can_approve', (u'Can approve requests to see encryption keys')),
                )

SECRET_TYPES = (('recovery_key', 'Recovery Key'),
                ('password', 'Password'))

class Secret(models.Model):
    computer = models.ForeignKey(Computer)
    secret = EncryptedCharField(max_length=256)
    secret_type =  models.CharField(max_length=256, choices=SECRET_TYPES, default='recovery_key')
    date_escrowed = models.DateTimeField(auto_now_add=True)

    def validate_unique(self, *args, **kwargs):
        if self.secret in [str(s) for s in self.__class__.objects.filter(secret_type=self.secret_type, computer=self.computer)]:
            raise ValidationError('already used')
        super(Secret, self).validate_unique(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.validate_unique()
        super(Secret, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.secret
    class Meta:
        ordering = ['-date_escrowed']

class Request(models.Model):
    secret = models.ForeignKey(Secret)
    #computer = models.ForeignKey(Computer, null=True, related_name='computers')
    requesting_user = models.ForeignKey(User, related_name='requesting_user')
    approved = models.NullBooleanField(verbose_name="Approved?")
    auth_user = models.ForeignKey(User, null=True, related_name='auth_user')
    reason_for_request = models.TextField()
    reason_for_approval = models.TextField(blank=True,null=True, verbose_name="Approval Notes")
    date_requested = models.DateTimeField(auto_now_add=True)
    date_approved = models.DateTimeField(blank=True,null=True)
    current = models.BooleanField(default=True)

    def __unicode__(self):
        return "%s - %s" % (self.secret, self.requesting_user)

server/forms.py
from django import forms
from models import *

class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ('reason_for_request',)

class ApproveForm(forms.ModelForm):
    #approved = forms.BooleanField()
    approved = forms.TypedChoiceField(coerce=lambda x: bool(int(x)),
                       choices=((1, 'Approved'),(0, 'Denied')),
                       widget=forms.RadioSelect,
                       label="Approved?"
                    )
    class Meta:
        model = Request
        fields = ('approved','reason_for_approval',)

class ComputerForm(forms.ModelForm):
    class Meta:
        model = Computer
        fields = ('serial','username','computername')

class SecretForm(forms.ModelForm):
    class Meta:
        model = Secret
        fields = ('secret_type','secret')

server/views.py
from models import *
from django.contrib.auth.decorators import login_required, permission_required
from django.template import RequestContext, Template, Context
import json
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.http import HttpResponse, Http404
from django.contrib.auth.models import Permission, User
from django.conf import settings
from django.core.context_processors import csrf
from django.shortcuts import render_to_response, get_object_or_404, redirect
from datetime import datetime, timedelta
from django.db.models import Q
from forms import *
from django.views.defaults import server_error
from django.core.mail import send_mail
from django.conf import settings
from django.core.urlresolvers import reverse
# Create your views here.

##clean up old requests
def cleanup():
    how_many_days = 7
    the_requests = Request.objects.filter(date_approved__lte=datetime.now()-timedelta(days=how_many_days)).filter(current=True)
    for the_req in the_requests:
        the_req.current = False
        the_req.save()

##index view
@login_required
def index(request):
    cleanup()
    #show table with all the keys
    computers = Computer.objects.all()

    if hasattr(settings, 'ALL_APPROVE'):
        if settings.ALL_APPROVE == True:
            permissions = Permission.objects.all()
            permission = Permission.objects.get(codename='can_approve')
            if request.user.has_perm('server.can_approve') == False:
                request.user.user_permissions.add(permission)
                request.user.save()
    ##get the number of oustanding requests - approved equals null

    outstanding = Request.objects.filter(approved__isnull=True)
    if hasattr(settings, 'APPROVE_OWN'):
        if settings.APPROVE_OWN == False:
            outstanding = outstanding.filter(~Q(requesting_user=request.user))
    c = {'user': request.user, 'computers':computers, 'outstanding':outstanding, }
    return render_to_response('server/index.html', c, context_instance=RequestContext(request))

##view to see computer info
@login_required
def computer_info(request, computer_id):
    cleanup()
    computer = get_object_or_404(Computer, pk=computer_id)
    can_request = None
    approved = None

    # Get the secrets, annotated with whethere there are approvals for them
    secrets = computer.secret_set.all().prefetch_related()

    for secret in secrets:
        secret.approved = Request.objects.filter(requesting_user=request.user).filter(approved=True).filter(current=True).filter(secret=secret)
        secret.pending = Request.objects.filter(requesting_user=request.user).filter(approved__isnull=True).filter(secret=secret)

    print vars(secrets)
    c = {'user': request.user, 'computer':computer, 'secrets':secrets }

    return render_to_response('server/computer_info.html', c, context_instance=RequestContext(request))

@login_required
def secret_info(request, secret_id):
    cleanup()

    secret = get_object_or_404(Secret, pk=secret_id)

    computer = secret.computer

    ##check if the user has outstanding request for this
    pending = secret.request_set.filter(requesting_user=request.user).filter(approved__isnull=True)
    if pending.count() == 0:
        can_request = True
    else:
        can_request = False
    ##if it's been approved, we'll show a link to retrieve the key
    approved = secret.request_set.filter(requesting_user=request.user).filter(approved=True).filter(current=True)
    requests = secret.request_set.all()

    c = {'user': request.user, 'computer':computer, 'can_request':can_request, 'approved':approved, 'secret':secret, 'requests':requests}
    if approved.count() != 0:
        return render_to_response('server/secret_approved_button.html', c, context_instance=RequestContext(request))
    else:
        return render_to_response('server/secret_request_button.html', c, context_instance=RequestContext(request))

##request key view
@login_required
def request(request, secret_id):
    ##we will auto approve this if the user has the right perms
    secret = get_object_or_404(Secret, pk=secret_id)
    approver = False
    if request.user.has_perm('server.can_approve'):
        approver = True

    if approver == True:
        if hasattr(settings, 'APPROVE_OWN'):
            if settings.APPROVE_OWN == False:
                approver = False
    c = {}
    c.update(csrf(request))
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            new_request = form.save(commit=False)
            new_request.requesting_user = request.user
            new_request.secret = secret
            new_request.save()
            if approver:
                new_request.auth_user = request.user
                new_request.approved = True
                new_request.date_approved = datetime.now()
                new_request.save()
            else:
                # User isn't an approver, send an email to all of the approvers
                perm = Permission.objects.get(codename='can_approve')
                users = User.objects.filter(Q(is_superuser=True) | Q(groups__permissions=perm) | Q(user_permissions=perm) ).distinct()

                if hasattr(settings, 'HOST_NAME'):
                    server_name = settings.HOST_NAME.rstrip('/')
                else:
                    server_name = 'http://crypt'
                if hasattr(settings, 'SEND_EMAIL'):
                    if settings.SEND_EMAIL == True:
                        for user in users:
                            if user.email:
                                email_message = """ There has been a new key request by %s. You can review this request at %s%s
                                """ % (request.user.username, server_name, reverse('server.views.approve', args=[new_request.id]))
                                email_sender = 'requests@%s' % request.META['SERVER_NAME']
                                send_mail('Crypt Key Request', email_message, email_sender,
        [user.email], fail_silently=True)

            ##if we're an approver, we'll redirect to the retrieve view
            if approver:
                return redirect('server.views.retrieve', new_request.id)
            else:
                return redirect('server.views.secret_info', secret.id)
    else:
        form = RequestForm()
    c = {'form': form, 'secret':secret, }
    return render_to_response('server/request.html', c, context_instance=RequestContext(request))



##retrieve key view
@login_required
def retrieve(request, request_id):
    cleanup()
    the_request = get_object_or_404(Request, pk=request_id)
    if the_request.approved == True and the_request.current==True:
        c = {'user': request.user, 'the_request':the_request, }
        return render_to_response('server/retrieve.html', c, context_instance=RequestContext(request))
    else:
        raise Http404

## approve key view
@permission_required('server.can_approve', login_url='/login/')
def approve(request, request_id):
    the_request = get_object_or_404(Request, pk=request_id)
    c = {}
    c.update(csrf(request))
    if request.method == 'POST':
        form = ApproveForm(request.POST, instance=the_request)
        if form.is_valid():
            new_request = form.save(commit=False)
            new_request.auth_user = request.user
            new_request.date_approved = datetime.now()
            new_request.save()

            # Send an email to the requester with a link to retrieve (or not)
            if hasattr(settings, 'HOST_NAME'):
                server_name = settings.HOST_NAME.rstrip('/')
            else:
                server_name = 'http://crypt'
            if new_request.approved == True:
                request_status = 'approved'
            elif new_request.approved == False:
                request_status = 'denied'
            if hasattr(settings, 'SEND_EMAIL'):
                if settings.SEND_EMAIL == True:
                    if new_request.requesting_user.email:
                        email_message = """ Your key request has been %s by %s. %s%s
                        """ % (request_status, request.user.username, server_name, reverse('server.views.secret_info', args=[new_request.id]))
                        email_sender = 'requests@%s' % request.META['SERVER_NAME']
                        send_mail('Crypt Key Request', email_message, email_sender,
    [new_request.requesting_user.email], fail_silently=True)
            return redirect('server.views.managerequests')
    else:
        form = ApproveForm(instance=the_request)
    c = {'form':form, 'user': request.user, 'the_request':the_request, }
    return render_to_response('server/approve.html', c, context_instance=RequestContext(request))

##manage requests
@permission_required('server.can_approve', login_url='/login/')
def managerequests(request):
    requests = Request.objects.filter(approved__isnull=True)
    if hasattr(settings, 'APPROVE_OWN'):
        if settings.APPROVE_OWN == False:
            requests = requests.filter(~Q(requesting_user=request.user))
    c = {'user': request.user, 'requests':requests, }
    return render_to_response('server/manage_requests.html', c, context_instance=RequestContext(request))

# Add new manual computer
@login_required
def new_computer(request):
    c = {}
    c.update(csrf(request))
    if request.method == 'POST':
        form = ComputerForm(request.POST)
        if form.is_valid():
            new_computer = form.save(commit=False)
            new_computer.save()
            form.save_m2m()
            return redirect('computer_info', new_computer.id)
    else:
        form = ComputerForm()
    c = {'form': form}
    return render_to_response('server/new_computer_form.html', c, context_instance=RequestContext(request))


@login_required
def new_secret(request, computer_id):
    c = {}
    c.update(csrf(request))
    computer = get_object_or_404(Computer, pk=computer_id)
    if request.method == 'POST':

server/templates/server/approve.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% block content %}
<h1>Approve Request</h1>
<p>{{ the_request.secret.computer.computername }} ({{ the_request.secret.computer.serial }})</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'approve' the_request.id %}" method="post">{% csrf_token %}


            {% bootstrap_form form %}

        <p><button type="submit" class="btn primary btn-default">Save</button></p>

    </form>
{% endblock %}

server/templates/server/computer_info.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            // "iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            // "sPaginationType": "bootstrap",
            // "bStateSave": true,
            // "aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block dropdown %}
<li><a href="{% url 'new_secret' computer.id %}"><span class="glyphicon glyphicon-plus"></span> New secret</a></li>
{% endblock %}

{% block nav %}
<li><a href="{% url 'home' %}"><i class="glyphicon glyphicon-chevron-left"></i> Home</a></li>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12 col-md-12">
    <h2>{{ computer.computername }}</h2>
    <h4>{{ computer.serial }}</h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-4 col-md-4">
        <table class="table table-bordered table-striped table-condensed">
            <tbody><tr><th>Username</th><td>{{ computer.username }}</td></tr>
            <tr><th>Computer Name</th><td>{{ computer.computername }}</td></tr>
            <tr><th>Serial Number</th><td>{{ computer.serial }}</td></tr>
            <tr><th>Escrow Date</th><td>{{ computer.last_checkin }}</td></tr>
        </tbody></table>
    </div>
    <div class="col-sm-4 col-md-4">
        {% block button %}
        {% endblock %}
    </div>
</div>


<div class="row">
    <div class="col-sm-12 col-md-12">
    <h3>Secrets</h3>
        <table class="table table-striped table-condensed groupList">
        <thead>

                <th>Secret Type</th>
                <th>Escrow Date</th>
                <th></th>
        </thead>
        <tbody>
            {% for secret in secrets %}
            <tr>

                <td>{{ secret.get_secret_type_display }}</td>
                <td>{{ secret.date_escrowed }}</td>
                <td><a class="btn btn-info btn-xs" href="{% url 'secret_info' secret.id %}">Info / Request</a></td>
            </tr>

            {% endfor %}
            </tbody>
        </table>
        </div>

</div>


{% endblock %}

server/templates/server/index.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            // "iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            // "sPaginationType": "bootstrap",
            // "bStateSave": true,
            // "aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block dropdown %}
<li><a href="{% url 'new_computer' %}"><span class="glyphicon glyphicon-plus"></span> New computer</a></li>
{% endblock %}
{% block nav %}
{% if perms.server.can_approve %}
    <li><a href="{% url 'managerequests' %}">Approve requests</a></li>
{% endif %}
{% endblock %}
{% block content %}
{% if perms.server.can_approve %}
    {% if outstanding.count > 0 %}
    <div class="alert alert-info">
        You have outstanding requests to approve.
    </div>
    {% endif %}
{% endif %}




    <table class="groupList table table-striped table-condensed">
    <thead>
        <tr>
          <th>Serial Number</th>
          <th>Computer Name</th>
          <th>User Name</th>
          <th>Date Stored</th>
          <th></th>
        </tr>
    </thead>
    <tbody>
        {% for computer in computers.all %}
        <tr><td><a href="{% url 'computer_info' computer.id %}">{{ computer.serial }}</a></td><td><a href="{% url 'computer_info' computer.id %}">{{ computer.computername }}</a></td><td>{{ computer.username }}</td><td>{{ computer.last_checkin }}</td><td><a class="btn btn-info btn-xs" href="{% url 'computer_info' computer.id %}">Info</a></td></tr>
        {% endfor %}
        </tbody>
</table>

{% endblock %}

server/templates/server/manage_requests.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            //"iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            //"sPaginationType": "bootstrap",
            //"bStateSave": true,
            //"aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block nav %}
<li><a href="{% url 'home' %}"><i class="glyphicon glyphicon-chevron-left"></i> Home</a></li>
{% endblock %}
{% block content %}
<h3>Key Requests</h3>
<table class="groupList table table-striped table-condensed">
    <thead>
        <tr>
          <th>Serial Number</th>
          <th>Computer Name</th>
          <th>Requested By</th>
          <th>Reason for Request</th>
          <th>Date Requested</th>
          <th></th>
        </tr>
    </thead>
    <tbody>
        {% for the_request in requests %}
        <tr><td><a href="{% url 'approve' the_request.id %}">{{ the_request.secret.computer.serial }}</a></td><td><a href="{% url 'approve' the_request.id %}">{{ the_request.secret.computer.computername }}</a></td><td>{{ the_request.requesting_user }}</td><td>{{ the_request.reason_for_request }}</td><td>{{ the_request.date_requested }}</td><td><a class="btn btn-primary btn-mini" href="{% url 'approve' the_request.id %}">Manage</a></td></tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

server/templates/server/new_computer_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
    <div class="col-md-4">
<h1>New Computer</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'new_computer' %}" method="post">{% csrf_token %}


            {% bootstrap_form form %}

        <p><button type="submit" class="btn btn-primary">Add new computer</button></p>

    </form>
</div>
</div>
{% endblock %}

server/templates/server/new_secret_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
    <div class="col-md-4">
<h1>New Secret</h1>
<h2>Computer: {{computer}}</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'new_secret' computer.id %}" method="post">{% csrf_token %}


            {% bootstrap_form form %}

        <p><button type="submit" class="btn btn-primary">Add new secret</button></p>

    </form>
</div>
</div>
{% endblock %}

server/templates/server/request.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<h1>Request Secret</h1>
<p>{{ secret.computer.computername }} ({{ secret.computer.serial }})</p>
<p>{{ secret.get_secret_type_display }} - {{ secret.date_escrowed }}</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'request' secret.id %}" method="post">{% csrf_token %}


            {% bootstrap_form form %}
        {% if not perms.server.can_approve %}
        <p><button type="submit" class="btn primary btn-default">Submit Request</button></p>
        {% else %}
        <p><button type="submit" class="btn primary btn-default">Retrieve Key</button></p>
        {% endif %}
    </form>
{% endblock %}

server/templates/server/retrieve.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            // "iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            // "sPaginationType": "bootstrap",
            // "bStateSave": true,
            // "aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block nav %}
<li><a href="{% url 'home' %}"><i class="glyphicon glyphicon-chevron-left"></i> Home</a></li>
{% endblock %}
{% block content %}
<div class="row">
    <h2>{{ computer.computername }}</h2>
    <h4>{{ computer.serial }}</h4>
</div>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <p><strong>{{ the_request.secret.get_secret_type_display }}:</strong><br /><code>{{ the_request.secret.secret }}</code></p>

        <p>This approval is valid for 7 days, after which you will need to submit another request for access.</p>
    </div>
</div>

{% endblock %}

server/templates/server/secret_approved_button.html
{% extends "server/secret_info.html" %}
{% block button %}
        {% for the_request in approved|slice:":1" %}
            <a href="{% url 'retrieve' the_request.id %}" class="btn btn-success btn-lg">Retrieve Key</a>

        {% endfor %}
{% endblock %}

server/templates/server/secret_info.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            // "iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            // "sPaginationType": "bootstrap",
            // "bStateSave": true,
            // "aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block nav %}
<li><a href="{% url 'computer_info' computer.id %}"><i class="glyphicon glyphicon-chevron-left"></i> Computer</a></li>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12 col-md-12">
    <h2>{{ computer.computername }}</h2>
    <h4>{{ computer.serial }}</h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-4 col-md-4">
        <table class="table table-bordered table-striped table-condensed">
            <tbody>
            <tr><th>Username</th><td>{{ computer.username }}</td></tr>
            <tr><th>Computer Name</th><td>{{ computer.computername }}</td></tr>
            <tr><th>Serial Number</th><td>{{ computer.serial }}</td></tr>
            <tr><th>Secret Type</th><td>{{ secret.get_secret_type_display }}</td></tr>
            <tr><th>Escrow Date</th><td>{{ secret.date_escrowed }}</td></tr>
        </tbody>
        </table>
    </div>
    <div class="col-sm-4 col-md-4">
        {% block button %}
        {% endblock %}
    </div>
</div>

{% if perms.server.can_approve %}
<div class="row">
    <div class="col-sm-12 col-md-12">
    <h3>Requests</h3>
        <table class="table groupList">
        <thead>
        <tr><th>Requesting User</th>
        <th>Reason for Request</th>
        <th>Date Requested</th>
        <th>Approved By</th>
        <th>Approval Notes</th>
        <th>Date Approved</th>
        </tr></thead>
        <tbody>
            {% for the_request in requests %}
            <tr>

                <td>{{ the_request.requesting_user }}</td>
                <td>{{ the_request.reason_for_request }}</td>
                <td>{{ the_request.date_requested }}</td>
                <td>{{ the_request.auth_user }}</td>
                <td>{{ the_request.reason_for_approval }}</td>
                <td>{{ the_request.date_approved }}</td>
            </tr>

            {% endfor %}
            </tbody>
        </table>
        </div>

</div>
{% endif %}

{% endblock %}

server/templates/server/secret_request_button.html
{% extends "server/secret_info.html" %}
{% block button %}
        {% if not perms.server.can_approve %}
            {% if can_request %}
            <a href="{% url 'request' secret.id %}" class="btn btn-large btn-info">Request Key</a>
            {% else %}
            <button class="btn btn-disabled btn-info">Request Pending</button>
            {% endif %}
            {% else %}
            <a href="{% url 'request' secret.id %}" class="btn btn-large btn-info">Get Key</a>
        {% endif %}
{% endblock %}